language: python
python:
  - "3.6"

stages:
  - test

before_install:

  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pytorch-cpu scipy -c pytorch
  # - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then pip install enum34; fi
  - source activate test-environment

  - pip install future
  - pip install pytest pytest-cov codecov
  - pip install mock

install:

  - pip install .

script:
  - python -m pytest -s tests

deploy:
  provider: pypi
  user: qubvel
  password:
    secure: AxdiUCtBKRE/UwLaMRnJtWTltm36tte2ihmGCocHNFvUZred+9VmeHa7TjPPvu+EAzAC2PQqXTjWzIwtW1L6x11bvwh/OQ5Agvx6CXSCDgGShHI/e1PvqVH+Cyy7jrrmTBU5T3e0AvFxOcYJV/oUZOIjy2q0YDvZYEy6325qwRFGJQPUlyrSLNGGBAJY81abSAxBBgDDKS2VwIqGpZAi1Y+x4u/21ZvU+XZCBWwPc7xpYqgTZobFbzWSkdniVRfXqsJuoOpMt7fSEUC68gXmh5eKOeVs32Gf1C4Q4wDw8a0/DqCx5Tfp8zLiub3xYcBcDTzL8Ue/iLcBEFDa0AgR0d5n2gXCFqhOcUh3wKHC+hw4eeHdtPFnRBFfhhCof8XUNfxIbQ2H98tbrQ4IVS1CHB3pgShTXys1rULO+AZdUeg/mK/RC8RspZWfhhCEpRU3bbhj6MMkVDl04cIzAqQBdolD754kc7fx/7DQfoeOMTSUGuUgtb17Jc0avJ15DP6DuxxF7Pt83GcUtcuv1gyVp2QxhPM64/yfOY/0FsucUL6/ZsVLQraRpW7okNSENN/+Ku7N79f3FelYNHWyZh7r899dxojyqcS3Q2VgcWw0BUQx3OZNZiSFLmXjioWJ/RhltVHxDBctRBCWVMnSpBJ/w71Yb0xjkD/9yuYrr+ZEA/g=
  on:
    tags: true
  skip_existing: true
  distributions: "sdist bdist_wheel"
