FROM anibali/pytorch:1.13.0-nocuda

WORKDIR /tmp/smp/

COPY ./requirements.txt /tmp/smp/requirements.txt
RUN pip install uv
RUN uv pip install -r requirements.txt
RUN uv pip install pytest mock

COPY . /tmp/smp/
RUN uv pip install .
